on: push
name: Finesse Nation CI/CD
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - run: flutter  config --enable-web
      - run: flutter  config --enable-linux-desktop
      - run: flutter  config --enable-macos-desktop
      - run: flutter  config --enable-windows-desktop
#      - run: flutter build web
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk,build/macos/Build/Products/Release/*.app"
          token: ${{ secrets.TOKEN }}
      - run: flutter build web
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: build/web


#  drive_android:
#    runs-on: macOS-latest
#    needs: build
#    steps:
#      - uses: actions/checkout@v1
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: 'dev'
#      - name: Integration tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: flutter drive --target=test_driver/app.dart